version: "3.7"
services:
  app:
    build:
      args:
        user: helper
        uid: 1000
      context: ./
      dockerfile: deployment/app/Dockerfile
    image: php-plant-helper
    container_name: plant-helper-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - plant-helper

  db:
    image: mysql:8.0.25
    container_name: plant-helper-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./deployment/mysql:/docker-entrypoint-initdb.d
    networks:
      - plant-helper

  nginx:
    image: nginx:1.17-alpine
    container_name: plant-helper-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./deployment/nginx:/etc/nginx/conf.d
    networks:
      - plant-helper

networks:
  plant-helper:
    driver: bridge
